def display_menu():
    print("\n=====JOB APPLICATION TRACKER=====")
    print("1. Add Application")
    print("2. View Applications")
    print("3. Update Status")
    print("4. Delete Application")
    print("5. View Analytics")
    print("6. Search Application")
    print("7. Export to CSV")
    print("8. Exit")